In [2]:
from sqlalchemy import create_engine
from dotenv import load_dotenv
from datetime import datetime, timedelta
import os
import requests
import pandas as pd
import time

In [3]:
def get_token(secret: str, url: str = "https://dep2.simondg.com/auth/login"):
    """Function for POST request to get access token using secret"""
    response = requests.post(url, json={"secret": secret})
    response.raise_for_status()  # Raises an error if the request fails
    return response.json()["access_token"]


def get_subgroup(token: str, subgroup_id: int):
    """Fetch students for a given subgroup"""
    url = f"https://dep2.simondg.com/students/{subgroup_id}"
    headers = {"Authorization": f"Bearer {token}"}
    response = requests.get(url, headers=headers)
    response.raise_for_status()
    return pd.DataFrame(response.json()["students"])

In [20]:
secret = os.getenv("SECRET")
if not secret:
    raise ValueError("SECRET not found in .env file")

token = get_token(secret)

# Example subgroup IDs
subgroup_ids = [6082490,5995907]


# subgroups dataframes
dfs = [get_subgroup(token, sg_id) for sg_id in subgroup_ids]

In [21]:
dfs

[   SUBGROEPID SUBGROEPCODE  DEELGROEPID  \
 0     6082490    MC/DATA/1        27495
 1     6082490    MC/DATA/1        27495
 2     6082490    MC/DATA/1        27495
 3     6082490    MC/DATA/1        27495

                                                 NAAM  \
 0  u_40d1c0b4832f87c5caf2b9226e79b454219c70f90698...
 1  u_bd60de66bbede5b67ec4757d5d1582bf849ba88a6598...
 2  u_5573097a6230aedef054da9d0faa056d32dddef571e7...
 3  u_daaa136a11fdb4e8e6abcfa62a8ac6308c54b1f63bc8...

                                                EMAIL
 0  u_e380c00a22b1d8c1ad26a11849fcc46151d31b5c8223...
 1  u_96c45275c04234c761ef2980da9a0a783f11e8b6cef1...
 2  u_107e217017cfa95d7247a2df030b70bad83fb6d3b703...
 3  u_edcb94b2ef3b52209cb2d51562c37089a6b444684af6...  ,
     SUBGROEPID    SUBGROEPCODE  DEELGROEPID  \
 0      5995907  PBA-TIN-TI/3C2        26689
 1      5995907  PBA-TIN-TI/3C2        26689
 2      5995907  PBA-TIN-TI/3C2        26689
 3      5995907  PBA-TIN-TI/3C2        26689
 4      5995907  PBA-TIN-TI/3C2        26689
 5      5995907  PBA-TIN-TI/3C2        26689
 6      5995907  PBA-TIN-TI/3C2        26689
 7      5995907  PBA-TIN-TI/3C2        26689
 8      5995907  PBA-TIN-TI/3C2        26689
 9      5995907  PBA-TIN-TI/3C2        26689
 10     5995907  PBA-TIN-TI/3C2        26689
 11     5995907  PBA-TIN-TI/3C2        26689
 12     5995907  PBA-TIN-TI/3C2        26689
 13     5995907  PBA-TIN-TI/3C2        26689
 14     5995907  PBA-TIN-TI/3C2        26689
 15     5995907  PBA-TIN-TI/3C2        26689
 16     5995907  PBA-TIN-TI/3C2        26689
 17     5995907  PBA-TIN-TI/3C2        26689
 18     5995907  PBA-TIN-TI/3C2        26689
 19     5995907  PBA-TIN-TI/3C2        26689
 20     5995907  PBA-TIN-TI/3C2        26689
 21     5995907  PBA-TIN-TI/3C2        26689
 22     5995907  PBA-TIN-TI/3C2        26689
 23     5995907  PBA-TIN-TI/3C2        26689
 24     5995907  PBA-TIN-TI/3C2        26689
 25     5995907  PBA-TIN-TI/3C2        26689
 26     5995907  PBA-TIN-TI/3C2        26689
 27     5995907  PBA-TIN-TI/3C2        26689
 28     5995907  PBA-TIN-TI/3C2        26689
 29     5995907  PBA-TIN-TI/3C2        26689
 30     5995907  PBA-TIN-TI/3C2        26689
 31     5995907  PBA-TIN-TI/3C2        26689
 32     5995907  PBA-TIN-TI/3C2        26689
 33     5995907  PBA-TIN-TI/3C2        26689
 34     5995907  PBA-TIN-TI/3C2        26689
 35     5995907  PBA-TIN-TI/3C2        26689
 36     5995907  PBA-TIN-TI/3C2        26689

                                                  NAAM  \
 0   u_fa8413bab74129cffc039f532092cecd4d412f98babf...
 1   u_2434d5ed68d17125281a772d3281245b9d4864fb698b...
 2   u_a8faf869ddf41f8520f0679ef53fbdb80a3be4faa9f4...
 3   u_1857708023cb428a0d610bd9be4a22762a3dd450a8dc...
 4   u_cc8e46d20e27b86c736d0cee7f7706dad8668dbc2c0f...
 5   u_e2d81ed2fdf955c46243cd2e5b12225590cad199e98a...
 6   u_c330882bb1542c665e8ffbdf09cdd9c647b595672a2f...
 7   u_9f3a19aa5e675a764e6a64fa5d362de45f00d7263051...
 8   u_0668a077b55214cbc79b60e04c7f8effa6b1494f6ad6...
 9   u_70c3d50a2e753bef1ac27c7f73247877f7fc15224974...
 10  u_c353eab76c559f4e97da69880073d779ff3ec6366029...
 11  u_00e147d8f116ea9a24fafe0a2620ee4be85d533ada8c...
 12  u_fc3c4b787127a2c8c53960722c8798bc335a2a0fa279...
 13  u_343ddea6c9a13396256fd253532023bf792b2a77cccc...
 14  u_283db2ddcbd809dbc5e6c26241e4f0db67d0ced1a238...
 15  u_1a999196d602b4ff478475b3ee06afd738cad7bb02f2...
 16  u_77cbfcb07fbc84b833f06c6e9a9b46982329bf8858e7...
 17  u_5685958dda802a6f8b5eae012afc68cf8b609a31222e...
 18  u_00e585e5a7d83d58c48f516c5a9a2e492d55bf3fb37f...
 19  u_ee835521bc6e31e537377bdba7096e078ecc4480d9ee...
 20  u_cded7059eaf13633085f6bcbfe55b888a2fbc868ee7c...
 21  u_af9b3d99cb8c8614ee53a856a8a77b9547d0eefcd693...
 22  u_41de5fb35752cba0633523c93ea8dfd9a1a273b00fb3...
 23  u_ff063da05de821da1bc001f11cecf2f938430ed02a7e...
 24  u_b01d5d791fb00f1b57c15b275c19475ffd3a2bcef8d0...
 25  u_a22e31cbf489d0704cd2a62cdfbfe64f72222e491e30...
 26  u_7d731c7c40e49c081528d6d103e91a27efababe93a05...
 27  u_34d3d45957dedd689f5fa6113a79f06f44d34052dd54...
 28  u_7bc516219d414703ed9f9bf83c3ca91352e0a58b3679...
 29  u_b88478d949e072a91e7ae701ae4567eed569c6ab6d00...
 30  u_477c4947367a07acc729de385a044fa231d6c7fd41d0...
 31  u_baeea601647baca08ab00a0ac5901d5596d9cbe6cdb6...
 32  u_9473c3d349883cce814747ba30ee173140db61b1f26b...
 33  u_fedc02d379f5ba2d26a7f0b787f8fe8d9ef2bc98da03...
 34  u_97d2c532aa9b370bcdb84f6a21f4e8f46400f67f1028...
 35  u_19da4e8b94ff684676b378ed941241d664aaa1eafa51...
 36  u_e4f49df95dd2cf114ff5344bbd8307f2be5d272b873b...

                                                 EMAIL
 0   u_d2c4f6edaa136ec1b7d3202c2bc9716e525f5e55fcab...
 1   u_bd00b117a705943034d30d2b54e92879b5c4f0e3ce37...
 2   u_352a9a0efbc6cb77cfd5cdcc7e5c2674dc15ff5327b1...
 3   u_8c36f5fb2310cdc9bbc33fb6e883f77180d2153323bc...
 4   u_2f737d92e09cf0e82755c6151c816ef08e2f42811b74...
 5   u_9e39729430e1932d192d124846e006b3be85a21c580f...
 6   u_011231e9e970021a92fe3bdf3daaba35971005127ff0...
 7   u_a5acdfd6bf70c501e1ab4d00d541b6ccbe38dd3f2fa4...
 8   u_e00126f9cd71fb927f3ff24df24e56b22171034b7ab8...
 9   u_dc33865bfcd0435139c2e75bc975af1300180640ed6f...
 10  u_c463a6cbb49d8b93760ba2c18a3c9a81178c3e2d4699...
 11  u_f9673b9d2140ec7b8d3f17b9f36edc62f1af8847e0dc...
 12  u_2850acdc152431cc41c8fac8b483a3b5459539856fd3...
 13  u_f053eff00056537da679df189ed3a1e66ca15dea2039...
 14  u_536052e8dce99828dc6c1688bf2ed3a602884f5897bf...
 15  u_67c125d7e8b6fa8a2310d4c0aec721a920bddf6e861a...
 16  u_8b1647e629d27777f63aa2c0873b78e017eb26821086...
 17  u_32931bedc8a2085e08a908f4d22e22d38744d7c26f31...
 18  u_d78c51dd9ba67fa8bd72c04bf1cc26e8217f984cbb34...
 19  u_4239ec66588049f0e94d6da3a1aefeeb89ead4405e39...
 20  u_22b03d4c5682b8c44f348200b5e8a2f25a1b564dfc4f...
 21  u_aebb7e74b521bd8a5d0f252b6ec0e250d8369179805e...
 22  u_8a3d82332e17ef9bd3f29d3ac4a9f47d47a1191bf012...
 23  u_75f2d7270af01536115535d1757a297c936d56262dfb...
 24  u_b94738c44bf40f7d10d7ee9dcf46fae50dc1869e0c61...
 25  u_b97b2765ec7f88a3e60f798160039d6fbe79211999de...
 26  u_aa8ea959b9428bd802294d09d872b2603fd718d5a014...
 27  u_49254118bdd8ed0428b36832e8809cb9d5319381f85a...
 28  u_2e3eced1498c7b34d5d3e37beb1bb37b61a72c2f3f14...
 29  u_d0c8bc2063091b2ef321856433569907c5bcec5decd1...
 30  u_35026c459c732d3e4e90dd243fd9f8ec8c4a5ca8ea16...
 31  u_68f9034f2170eeef40d5b58ae6d4ec448b5232b5e2c1...
 32  u_6079055ba935616120e27fa8a18e368b286da9afb61d...
 33  u_b96bb82db9e8eb2de8b7d028434322ec702e6abde54b...
 34  u_34cdffdc2135c8a20bd53fa87985c38e38c45a9fff83...
 35  u_c234f1198ac6cd7244cb39d6c74625a5587d003c9a77...
 36  u_454cdfd2e7c1c10044f3d10f1db2d822472f6e8a5233...  ]

In [22]:
df_all = pd.concat(dfs, ignore_index=True)
df_all

,SUBGROEPID,SUBGROEPCODE,DEELGROEPID,NAAM,EMAIL
0,6082490,MC/DATA/1,27495,u_40d1c0b4832f87c5caf2b9226e79b454219c70f90698...,u_e380c00a22b1d8c1ad26a11849fcc46151d31b5c8223...
1,6082490,MC/DATA/1,27495,u_bd60de66bbede5b67ec4757d5d1582bf849ba88a6598...,u_96c45275c04234c761ef2980da9a0a783f11e8b6cef1...
2,6082490,MC/DATA/1,27495,u_5573097a6230aedef054da9d0faa056d32dddef571e7...,u_107e217017cfa95d7247a2df030b70bad83fb6d3b703...
3,6082490,MC/DATA/1,27495,u_daaa136a11fdb4e8e6abcfa62a8ac6308c54b1f63bc8...,u_edcb94b2ef3b52209cb2d51562c37089a6b444684af6...
4,5995907,PBA-TIN-TI/3C2,26689,u_fa8413bab74129cffc039f532092cecd4d412f98babf...,u_d2c4f6edaa136ec1b7d3202c2bc9716e525f5e55fcab...
5,5995907,PBA-TIN-TI/3C2,26689,u_2434d5ed68d17125281a772d3281245b9d4864fb698b...,u_bd00b117a705943034d30d2b54e92879b5c4f0e3ce37...
6,5995907,PBA-TIN-TI/3C2,26689,u_a8faf869ddf41f8520f0679ef53fbdb80a3be4faa9f4...,u_352a9a0efbc6cb77cfd5cdcc7e5c2674dc15ff5327b1...
7,5995907,PBA-TIN-TI/3C2,26689,u_1857708023cb428a0d610bd9be4a22762a3dd450a8dc...,u_8c36f5fb2310cdc9bbc33fb6e883f77180d2153323bc...
8,5995907,PBA-TIN-TI/3C2,26689,u_cc8e46d20e27b86c736d0cee7f7706dad8668dbc2c0f...,u_2f737d92e09cf0e82755c6151c816ef08e2f42811b74...
9,5995907,PBA-TIN-TI/3C2,26689,u_e2d81ed2fdf955c46243cd2e5b12225590cad199e98a...,u_9e39729430e1932d192d124846e006b3be85a21c580f...
10,5995907,PBA-TIN-TI/3C2,26689,u_c330882bb1542c665e8ffbdf09cdd9c647b595672a2f...,u_011231e9e970021a92fe3bdf3daaba35971005127ff0...
11,5995907,PBA-TIN-TI/3C2,26689,u_9f3a19aa5e675a764e6a64fa5d362de45f00d7263051...,u_a5acdfd6bf70c501e1ab4d00d541b6ccbe38dd3f2fa4...
12,5995907,PBA-TIN-TI/3C2,26689,u_0668a077b55214cbc79b60e04c7f8effa6b1494f6ad6...,u_e00126f9cd71fb927f3ff24df24e56b22171034b7ab8...
13,5995907,PBA-TIN-TI/3C2,26689,u_70c3d50a2e753bef1ac27c7f73247877f7fc15224974...,u_dc33865bfcd0435139c2e75bc975af1300180640ed6f...
14,5995907,PBA-TIN-TI/3C2,26689,u_c353eab76c559f4e97da69880073d779ff3ec6366029...,u_c463a6cbb49d8b93760ba2c18a3c9a81178c3e2d4699...
15,5995907,PBA-TIN-TI/3C2,26689,u_00e147d8f116ea9a24fafe0a2620ee4be85d533ada8c...,u_f9673b9d2140ec7b8d3f17b9f36edc62f1af8847e0dc...
16,5995907,PBA-TIN-TI/3C2,26689,u_fc3c4b787127a2c8c53960722c8798bc335a2a0fa279...,u_2850acdc152431cc41c8fac8b483a3b5459539856fd3...
17,5995907,PBA-TIN-TI/3C2,26689,u_343ddea6c9a13396256fd253532023bf792b2a77cccc...,u_f053eff00056537da679df189ed3a1e66ca15dea2039...
18,5995907,PBA-TIN-TI/3C2,26689,u_283db2ddcbd809dbc5e6c26241e4f0db67d0ced1a238...,u_536052e8dce99828dc6c1688bf2ed3a602884f5897bf...
19,5995907,PBA-TIN-TI/3C2,26689,u_1a999196d602b4ff478475b3ee06afd738cad7bb02f2...,u_67c125d7e8b6fa8a2310d4c0aec721a920bddf6e861a...
20,5995907,PBA-TIN-TI/3C2,26689,u_77cbfcb07fbc84b833f06c6e9a9b46982329bf8858e7...,u_8b1647e629d27777f63aa2c0873b78e017eb26821086...
21,5995907,PBA-TIN-TI/3C2,26689,u_5685958dda802a6f8b5eae012afc68cf8b609a31222e...,u_32931bedc8a2085e08a908f4d22e22d38744d7c26f31...
22,5995907,PBA-TIN-TI/3C2,26689,u_00e585e5a7d83d58c48f516c5a9a2e492d55bf3fb37f...,u_d78c51dd9ba67fa8bd72c04bf1cc26e8217f984cbb34...
23,5995907,PBA-TIN-TI/3C2,26689,u_ee835521bc6e31e537377bdba7096e078ecc4480d9ee...,u_4239ec66588049f0e94d6da3a1aefeeb89ead4405e39...
24,5995907,PBA-TIN-TI/3C2,26689,u_cded7059eaf13633085f6bcbfe55b888a2fbc868ee7c...,u_22b03d4c5682b8c44f348200b5e8a2f25a1b564dfc4f...
25,5995907,PBA-TIN-TI/3C2,26689,u_af9b3d99cb8c8614ee53a856a8a77b9547d0eefcd693...,u_aebb7e74b521bd8a5d0f252b6ec0e250d8369179805e...
26,5995907,PBA-TIN-TI/3C2,26689,u_41de5fb35752cba0633523c93ea8dfd9a1a273b00fb3...,u_8a3d82332e17ef9bd3f29d3ac4a9f47d47a1191bf012...
27,5995907,PBA-TIN-TI/3C2,26689,u_ff063da05de821da1bc001f11cecf2f938430ed02a7e...,u_75f2d7270af01536115535d1757a297c936d56262dfb...
28,5995907,PBA-TIN-TI/3C2,26689,u_b01d5d791fb00f1b57c15b275c19475ffd3a2bcef8d0...,u_b94738c44bf40f7d10d7ee9dcf46fae50dc1869e0c61...
29,5995907,PBA-TIN-TI/3C2,26689,u_a22e31cbf489d0704cd2a62cdfbfe64f72222e491e30...,u_b97b2765ec7f88a3e60f798160039d6fbe79211999de...
30,5995907,PBA-TIN-TI/3C2,26689,u_7d731c7c40e49c081528d6d103e91a27efababe93a05...,u_aa8ea959b9428bd802294d09d872b2603fd718d5a014...
31,5995907,PBA-TIN-TI/3C2,26689,u_34d3d45957dedd689f5fa6113a79f06f44d34052dd54...,u_49254118bdd8ed0428b36832e8809cb9d5319381f85a...
32,5995907,PBA-TIN-TI/3C2,26689,u_7bc516219d414703ed9f9bf83c3ca91352e0a58b3679...,u_2e3eced1498c7b34d5d3e37beb1bb37b61a72c2f3f14...
33,5995907,PBA-TIN-TI/3C2,26689,u_b88478d949e072a91e7ae701ae4567eed569c6ab6d00...,u_d0c8bc2063091b2ef321856433569907c5bcec5decd1...
34,5995907,PBA-TIN-TI/3C2,26689,u_477c4947367a07acc729de385a044fa231d6c7fd41d0...,u_35026c459c732d3e4e90dd243fd9f8ec8c4a5ca8ea16...
35,5995907,PBA-TIN-TI/3C2,26689,u_baeea601647baca08ab00a0ac5901d5596d9cbe6cdb6...,u_68f9034f2170eeef40d5b58ae6d4ec448b5232b5e2c1...
36,5995907,PBA-TIN-TI/3C2,26689,u_9473c3d349883cce814747ba30ee173140db61b1f26b...,u_6079055ba935616120e27fa8a18e368b286da9afb61d...
37,5995907,PBA-TIN-TI/3C2,26689,u_fedc02d379f5ba2d26a7f0b787f8fe8d9ef2bc98da03...,u_b96bb82db9e8eb2de8b7d028434322ec702e6abde54b...
38,5995907,PBA-TIN-TI/3C2,26689,u_97d2c532aa9b370bcdb84f6a21f4e8f46400f67f1028...,u_34cdffdc2135c8a20bd53fa87985c38e38c45a9fff83...
39,5995907,PBA-TIN-TI/3C2,26689,u_19da4e8b94ff684676b378ed941241d664aaa1eafa51...,u_c234f1198ac6cd7244cb39d6c74625a5587d003c9a77...
40,5995907,PBA-TIN-TI/3C2,26689,u_e4f49df95dd2cf114ff5344bbd8307f2be5d272b873b...,u_454cdfd2e7c1c10044f3d10f1db2d822472f6e8a5233...

In [23]:
# Drop duplicates by a unique identifier (EMAIL or NAAM)
df_unique = df_all.drop_duplicates(subset=["EMAIL"])

# Show total unique students
print(f"Total unique students across all subgroups: {len(df_unique)}")

# Optional: show counts per subgroup and overall
print(df_all.groupby("SUBGROEPID").size())
df_unique

Total unique students across all subgroups: 41
SUBGROEPID
5995907    37
6082490     4
dtype: int64

,SUBGROEPID,SUBGROEPCODE,DEELGROEPID,NAAM,EMAIL
0,6082490,MC/DATA/1,27495,u_40d1c0b4832f87c5caf2b9226e79b454219c70f90698...,u_e380c00a22b1d8c1ad26a11849fcc46151d31b5c8223...
1,6082490,MC/DATA/1,27495,u_bd60de66bbede5b67ec4757d5d1582bf849ba88a6598...,u_96c45275c04234c761ef2980da9a0a783f11e8b6cef1...
2,6082490,MC/DATA/1,27495,u_5573097a6230aedef054da9d0faa056d32dddef571e7...,u_107e217017cfa95d7247a2df030b70bad83fb6d3b703...
3,6082490,MC/DATA/1,27495,u_daaa136a11fdb4e8e6abcfa62a8ac6308c54b1f63bc8...,u_edcb94b2ef3b52209cb2d51562c37089a6b444684af6...
4,5995907,PBA-TIN-TI/3C2,26689,u_fa8413bab74129cffc039f532092cecd4d412f98babf...,u_d2c4f6edaa136ec1b7d3202c2bc9716e525f5e55fcab...
5,5995907,PBA-TIN-TI/3C2,26689,u_2434d5ed68d17125281a772d3281245b9d4864fb698b...,u_bd00b117a705943034d30d2b54e92879b5c4f0e3ce37...
6,5995907,PBA-TIN-TI/3C2,26689,u_a8faf869ddf41f8520f0679ef53fbdb80a3be4faa9f4...,u_352a9a0efbc6cb77cfd5cdcc7e5c2674dc15ff5327b1...
7,5995907,PBA-TIN-TI/3C2,26689,u_1857708023cb428a0d610bd9be4a22762a3dd450a8dc...,u_8c36f5fb2310cdc9bbc33fb6e883f77180d2153323bc...
8,5995907,PBA-TIN-TI/3C2,26689,u_cc8e46d20e27b86c736d0cee7f7706dad8668dbc2c0f...,u_2f737d92e09cf0e82755c6151c816ef08e2f42811b74...
9,5995907,PBA-TIN-TI/3C2,26689,u_e2d81ed2fdf955c46243cd2e5b12225590cad199e98a...,u_9e39729430e1932d192d124846e006b3be85a21c580f...
10,5995907,PBA-TIN-TI/3C2,26689,u_c330882bb1542c665e8ffbdf09cdd9c647b595672a2f...,u_011231e9e970021a92fe3bdf3daaba35971005127ff0...
11,5995907,PBA-TIN-TI/3C2,26689,u_9f3a19aa5e675a764e6a64fa5d362de45f00d7263051...,u_a5acdfd6bf70c501e1ab4d00d541b6ccbe38dd3f2fa4...
12,5995907,PBA-TIN-TI/3C2,26689,u_0668a077b55214cbc79b60e04c7f8effa6b1494f6ad6...,u_e00126f9cd71fb927f3ff24df24e56b22171034b7ab8...
13,5995907,PBA-TIN-TI/3C2,26689,u_70c3d50a2e753bef1ac27c7f73247877f7fc15224974...,u_dc33865bfcd0435139c2e75bc975af1300180640ed6f...
14,5995907,PBA-TIN-TI/3C2,26689,u_c353eab76c559f4e97da69880073d779ff3ec6366029...,u_c463a6cbb49d8b93760ba2c18a3c9a81178c3e2d4699...
15,5995907,PBA-TIN-TI/3C2,26689,u_00e147d8f116ea9a24fafe0a2620ee4be85d533ada8c...,u_f9673b9d2140ec7b8d3f17b9f36edc62f1af8847e0dc...
16,5995907,PBA-TIN-TI/3C2,26689,u_fc3c4b787127a2c8c53960722c8798bc335a2a0fa279...,u_2850acdc152431cc41c8fac8b483a3b5459539856fd3...
17,5995907,PBA-TIN-TI/3C2,26689,u_343ddea6c9a13396256fd253532023bf792b2a77cccc...,u_f053eff00056537da679df189ed3a1e66ca15dea2039...
18,5995907,PBA-TIN-TI/3C2,26689,u_283db2ddcbd809dbc5e6c26241e4f0db67d0ced1a238...,u_536052e8dce99828dc6c1688bf2ed3a602884f5897bf...
19,5995907,PBA-TIN-TI/3C2,26689,u_1a999196d602b4ff478475b3ee06afd738cad7bb02f2...,u_67c125d7e8b6fa8a2310d4c0aec721a920bddf6e861a...
20,5995907,PBA-TIN-TI/3C2,26689,u_77cbfcb07fbc84b833f06c6e9a9b46982329bf8858e7...,u_8b1647e629d27777f63aa2c0873b78e017eb26821086...
21,5995907,PBA-TIN-TI/3C2,26689,u_5685958dda802a6f8b5eae012afc68cf8b609a31222e...,u_32931bedc8a2085e08a908f4d22e22d38744d7c26f31...
22,5995907,PBA-TIN-TI/3C2,26689,u_00e585e5a7d83d58c48f516c5a9a2e492d55bf3fb37f...,u_d78c51dd9ba67fa8bd72c04bf1cc26e8217f984cbb34...
23,5995907,PBA-TIN-TI/3C2,26689,u_ee835521bc6e31e537377bdba7096e078ecc4480d9ee...,u_4239ec66588049f0e94d6da3a1aefeeb89ead4405e39...
24,5995907,PBA-TIN-TI/3C2,26689,u_cded7059eaf13633085f6bcbfe55b888a2fbc868ee7c...,u_22b03d4c5682b8c44f348200b5e8a2f25a1b564dfc4f...
25,5995907,PBA-TIN-TI/3C2,26689,u_af9b3d99cb8c8614ee53a856a8a77b9547d0eefcd693...,u_aebb7e74b521bd8a5d0f252b6ec0e250d8369179805e...
26,5995907,PBA-TIN-TI/3C2,26689,u_41de5fb35752cba0633523c93ea8dfd9a1a273b00fb3...,u_8a3d82332e17ef9bd3f29d3ac4a9f47d47a1191bf012...
27,5995907,PBA-TIN-TI/3C2,26689,u_ff063da05de821da1bc001f11cecf2f938430ed02a7e...,u_75f2d7270af01536115535d1757a297c936d56262dfb...
28,5995907,PBA-TIN-TI/3C2,26689,u_b01d5d791fb00f1b57c15b275c19475ffd3a2bcef8d0...,u_b94738c44bf40f7d10d7ee9dcf46fae50dc1869e0c61...
29,5995907,PBA-TIN-TI/3C2,26689,u_a22e31cbf489d0704cd2a62cdfbfe64f72222e491e30...,u_b97b2765ec7f88a3e60f798160039d6fbe79211999de...
30,5995907,PBA-TIN-TI/3C2,26689,u_7d731c7c40e49c081528d6d103e91a27efababe93a05...,u_aa8ea959b9428bd802294d09d872b2603fd718d5a014...
31,5995907,PBA-TIN-TI/3C2,26689,u_34d3d45957dedd689f5fa6113a79f06f44d34052dd54...,u_49254118bdd8ed0428b36832e8809cb9d5319381f85a...
32,5995907,PBA-TIN-TI/3C2,26689,u_7bc516219d414703ed9f9bf83c3ca91352e0a58b3679...,u_2e3eced1498c7b34d5d3e37beb1bb37b61a72c2f3f14...
33,5995907,PBA-TIN-TI/3C2,26689,u_b88478d949e072a91e7ae701ae4567eed569c6ab6d00...,u_d0c8bc2063091b2ef321856433569907c5bcec5decd1...
34,5995907,PBA-TIN-TI/3C2,26689,u_477c4947367a07acc729de385a044fa231d6c7fd41d0...,u_35026c459c732d3e4e90dd243fd9f8ec8c4a5ca8ea16...
35,5995907,PBA-TIN-TI/3C2,26689,u_baeea601647baca08ab00a0ac5901d5596d9cbe6cdb6...,u_68f9034f2170eeef40d5b58ae6d4ec448b5232b5e2c1...
36,5995907,PBA-TIN-TI/3C2,26689,u_9473c3d349883cce814747ba30ee173140db61b1f26b...,u_6079055ba935616120e27fa8a18e368b286da9afb61d...
37,5995907,PBA-TIN-TI/3C2,26689,u_fedc02d379f5ba2d26a7f0b787f8fe8d9ef2bc98da03...,u_b96bb82db9e8eb2de8b7d028434322ec702e6abde54b...
38,5995907,PBA-TIN-TI/3C2,26689,u_97d2c532aa9b370bcdb84f6a21f4e8f46400f67f1028...,u_34cdffdc2135c8a20bd53fa87985c38e38c45a9fff83...
39,5995907,PBA-TIN-TI/3C2,26689,u_19da4e8b94ff684676b378ed941241d664aaa1eafa51...,u_c234f1198ac6cd7244cb39d6c74625a5587d003c9a77...
40,5995907,PBA-TIN-TI/3C2,26689,u_e4f49df95dd2cf114ff5344bbd8307f2be5d272b873b...,u_454cdfd2e7c1c10044f3d10f1db2d822472f6e8a5233...