In [4]:
import os
import argparse
import pandas as pd
import shutil
from datetime import datetime
from dateutil import parser as dateparser
import glob

In [5]:
# Archive helper: call this AFTER processing a file successfully.
ARCHIVE_DIR = "../data/archived"   
os.makedirs(ARCHIVE_DIR, exist_ok=True)

def _unique_target_path(target_dir, filename):
    dest = os.path.join(target_dir, filename)
    if not os.path.exists(dest):
        return dest
    ts = datetime.now().strftime("%Y%m%dT%H%M%SZ")
    name, ext = os.path.splitext(filename)
    return os.path.join(target_dir, f"{name}__{ts}{ext}")

def archive_file(src_path, archive_dir=ARCHIVE_DIR):
    if not os.path.exists(src_path):
        raise FileNotFoundError(f"Source not found: {src_path}")
    os.makedirs(archive_dir, exist_ok=True)
    filename = os.path.basename(src_path)
    dest = _unique_target_path(archive_dir, filename)
    try:
        shutil.move(src_path, dest)
        return dest
    except Exception as e:
        # fallback copy+remove
        try:
            shutil.copy2(src_path, dest)
            os.remove(src_path)
            return dest
        except Exception as e2:
            raise RuntimeError(f"Failed to archive {src_path}. move error: {e}; copy fallback: {e2}")

In [6]:
# file_path = "../data/reservations/TEreservations_20250930_20251001.csv"  
# df = pd.read_csv(file_path, sep=';')

In [7]:
DATA_FOLDER = "../data"
INPUT_FOLDER = "../data/reservations"
os.makedirs(DATA_FOLDER, exist_ok=True)
OUTPUT_FILE = os.path.join(DATA_FOLDER, "all_TEreservations_clean.csv")

In [8]:
csv_files = sorted(glob.glob(os.path.join(INPUT_FOLDER, "TEreservations_*.csv")))

if not csv_files:
    print("No matching CSV files found in folder 'data'.")
else:
    print(f"Found {len(csv_files)} CSV files:")
    for f in csv_files:
        print("  -", os.path.basename(f))

Found 9 CSV files:
  - TEreservations_20251006_20251007.csv
  - TEreservations_20251007_20251008.csv
  - TEreservations_20251008_20251009.csv
  - TEreservations_20251009_20251010.csv
  - TEreservations_20251010_20251011.csv
  - TEreservations_20251011_20251012.csv
  - TEreservations_20251012_20251013.csv
  - TEreservations_20251013_20251014.csv
  - TEreservations_20251014_20251015.csv

In [9]:
if csv_files:
    sample_file = csv_files[0]
    print(f"Inspecting sample file: {os.path.basename(sample_file)}")
    
    df_sample = pd.read_csv(sample_file, sep=';', low_memory=False)
    display(df_sample.head(10))
else:
    print("No sample file to inspect.")

Inspecting sample file: TEreservations_20251006_20251007.csv

,Id,Start,End,Updated,UpdatedBy,Status,ReasonTeacher,ReasonRoom,InternExtern,Department,...,MobileEquipment,Classgroups,TeacherIds,OlodPointers,Rooms,TrajectoryPart,GroupHogent,Person,Student,Invigilator
0,475972,10/28/2025 10:30:00,10/28/2025 12:30:00,10/06/2025 07:49:20,jan.soons+1@hogent.be,Confirmed,NaN,NaN,NaN,UGent,...,NaN,NaN,NaN,NaN,01.02.130.006|01.02.130.014,NaN,NaN,NaN,NaN,NaN
1,475973,10/16/2025 10:30:00,10/16/2025 12:30:00,10/06/2025 08:05:22,suzanne.naert+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,...,NaN,5922436,869611223154,193503,01.20.120.158,23621|23626|22996|23619,NaN,NaN,NaN,NaN
2,413184,10/09/2025 08:15:00,10/09/2025 10:15:00,10/06/2025 08:05:34,NaN,Cancelled,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,437293,10/02/2025 15:45:00,10/02/2025 16:45:00,10/06/2025 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,...,NaN,5940368,869792953462,195982,21.03.125.047,23283,NaN,NaN,NaN,NaN
4,437294,10/09/2025 15:45:00,10/09/2025 16:45:00,10/06/2025 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,...,NaN,5940368,869792953462,195982,21.03.125.047,23283,NaN,NaN,NaN,NaN
5,437295,10/16/2025 15:45:00,10/16/2025 16:45:00,10/06/2025 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,...,NaN,5940368,869792953462,195982,21.03.125.047,23283,NaN,NaN,NaN,NaN
6,437296,10/23/2025 15:45:00,10/23/2025 16:45:00,10/06/2025 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,...,NaN,5940368,869792953462,195982,21.03.125.047,23283,NaN,NaN,NaN,NaN
7,437297,10/30/2025 15:45:00,10/30/2025 16:45:00,10/06/2025 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,...,NaN,5940368,869792953462,195982,21.03.125.047,23283,NaN,NaN,NaN,NaN
8,437298,11/06/2025 15:45:00,11/06/2025 16:45:00,10/06/2025 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,...,NaN,5940368,869792953462,195982,21.03.125.047,23283,NaN,NaN,NaN,NaN
9,437299,11/13/2025 15:45:00,11/13/2025 16:45:00,10/06/2025 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,...,NaN,5940368,869792953462,195982,21.03.125.047,23283,NaN,NaN,NaN,NaN

In [10]:
all_data = []
for file in csv_files:
    try:
        temp_df = pd.read_csv(file, sep=';', low_memory=False)
        temp_df['source_file'] = os.path.basename(file)
        all_data.append(temp_df)
        try:
            archived_path = archive_file(file)
            print(f"Archived processed file: {os.path.basename(file)} -> {archived_path}")
        except Exception as ar_err:
            print(f"Warning: failed to archive {file}: {ar_err}")

    except Exception as e:
        print(f"Error reading {file}: {e}")

if all_data:
    df = pd.concat(all_data, ignore_index=True)
    print(f"Combined {len(all_data)} files — total rows: {len(df):,}")
else:
    df = pd.DataFrame()
    print("No data combined.")

Archived processed file: TEreservations_20251006_20251007.csv -> ../data/archived\TEreservations_20251006_20251007.csv
Archived processed file: TEreservations_20251007_20251008.csv -> ../data/archived\TEreservations_20251007_20251008.csv
Archived processed file: TEreservations_20251008_20251009.csv -> ../data/archived\TEreservations_20251008_20251009.csv
Archived processed file: TEreservations_20251009_20251010.csv -> ../data/archived\TEreservations_20251009_20251010.csv
Archived processed file: TEreservations_20251010_20251011.csv -> ../data/archived\TEreservations_20251010_20251011.csv
Archived processed file: TEreservations_20251011_20251012.csv -> ../data/archived\TEreservations_20251011_20251012.csv
Archived processed file: TEreservations_20251012_20251013.csv -> ../data/archived\TEreservations_20251012_20251013.csv
Archived processed file: TEreservations_20251013_20251014.csv -> ../data/archived\TEreservations_20251013_20251014.csv
Archived processed file: TEreservations_20251014_20251015.csv -> ../data/archived\TEreservations_20251014_20251015.csv
Combined 9 files — total rows: 3,313

In [11]:
if not df.empty:
    relevant_cols = [
        'Id', 'Start', 'End', 'Updated', 'UpdatedBy', 'Status',
        'WorkFormCourse', 'WorkFormExam', 'WorkFormEvaluation',
        'LearningEnvironment', 'ExamEnvironment', 'Classgroups',
        'TeacherIds', 'OlodPointers', 'Rooms', 'TrajectoryPart'
    ]
    
    # Keep only relevant columns and existing ones
    df_clean = df[[c for c in relevant_cols if c in df.columns]].copy()

    # Remove cancelled or missing status rows
    df_clean = df_clean[df_clean['Status'].str.lower() != 'cancelled']

    # Convert date columns to datetime if possible
    for col in ['Start', 'End', 'Updated']:
        if col in df_clean.columns:
            df_clean[col] = pd.to_datetime(df_clean[col], errors='coerce', dayfirst=True)

    print(f"Cleaned data shape: {df_clean.shape}")
    display(df_clean.head(10))
else:
    print("No data to clean.")

Cleaned data shape: (2907, 16)

C:\Users\yoran\AppData\Local\Temp\ipykernel_15640\1909578771.py:18: UserWarning: Parsing dates in %m/%d/%Y %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_clean[col] = pd.to_datetime(df_clean[col], errors='coerce', dayfirst=True)
C:\Users\yoran\AppData\Local\Temp\ipykernel_15640\1909578771.py:18: UserWarning: Parsing dates in %m/%d/%Y %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_clean[col] = pd.to_datetime(df_clean[col], errors='coerce', dayfirst=True)

,Id,Start,End,Updated,UpdatedBy,Status,WorkFormCourse,WorkFormExam,WorkFormEvaluation,LearningEnvironment,ExamEnvironment,Classgroups,TeacherIds,OlodPointers,Rooms,TrajectoryPart
0,475972,2025-10-28 10:30:00,2025-10-28 12:30:00,2025-06-10 07:49:20,jan.soons+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01.02.130.006|01.02.130.014,NaN
1,475973,2025-10-16 10:30:00,2025-10-16 12:30:00,2025-06-10 08:05:22,suzanne.naert+1@hogent.be,Confirmed,Activerend hoorcollege,NaN,NaN,NaN,NaN,5922436,869611223154,193503,01.20.120.158,23621|23626|22996|23619
3,437293,2025-10-02 15:45:00,2025-10-02 16:45:00,2025-06-10 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,Onderwijsleergesprek,NaN,NaN,Digitaal (laptop/PC),NaN,5940368,869792953462,195982,21.03.125.047,23283
4,437294,2025-10-09 15:45:00,2025-10-09 16:45:00,2025-06-10 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,Onderwijsleergesprek,NaN,NaN,Digitaal (laptop/PC),NaN,5940368,869792953462,195982,21.03.125.047,23283
5,437295,2025-10-16 15:45:00,2025-10-16 16:45:00,2025-06-10 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,Onderwijsleergesprek,NaN,NaN,Digitaal (laptop/PC),NaN,5940368,869792953462,195982,21.03.125.047,23283
6,437296,2025-10-23 15:45:00,2025-10-23 16:45:00,2025-06-10 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,Onderwijsleergesprek,NaN,NaN,Digitaal (laptop/PC),NaN,5940368,869792953462,195982,21.03.125.047,23283
7,437297,2025-10-30 15:45:00,2025-10-30 16:45:00,2025-06-10 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,Onderwijsleergesprek,NaN,NaN,Digitaal (laptop/PC),NaN,5940368,869792953462,195982,21.03.125.047,23283
8,437298,2025-11-06 15:45:00,2025-11-06 16:45:00,2025-06-10 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,Onderwijsleergesprek,NaN,NaN,Digitaal (laptop/PC),NaN,5940368,869792953462,195982,21.03.125.047,23283
9,437299,2025-11-13 15:45:00,2025-11-13 16:45:00,2025-06-10 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,Onderwijsleergesprek,NaN,NaN,Digitaal (laptop/PC),NaN,5940368,869792953462,195982,21.03.125.047,23283
10,437301,2025-11-27 15:45:00,2025-11-27 16:45:00,2025-06-10 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,Onderwijsleergesprek,NaN,NaN,Digitaal (laptop/PC),NaN,5940368,869792953462,195982,21.03.125.047,23283

In [12]:
if not df_clean.empty:
    df_clean.to_csv(OUTPUT_FILE, index=False, sep=';')
    print(f"Saved cleaned file to: {OUTPUT_FILE}")
else:
    print("Nothing to save — cleaned DataFrame is empty.")

Saved cleaned file to: ../data\all_TEreservations_clean.csv

In [13]:
if not df_clean.empty:
    print("Summary:")
    print(f"Total rows: {len(df_clean):,}")
    print(f"Unique Teachers: {df_clean['UpdatedBy'].nunique() if 'UpdatedBy' in df_clean else 0}")
    print(f"Date range: {df_clean['Start'].min()} → {df_clean['End'].max()}")
    print("\nMissing values per column:")
    display(df_clean.isna().sum())
else:
    print("No data to summarize.")

Summary:
Total rows: 2,907
Unique Teachers: 197
Date range: 2025-03-19 18:45:00 → 2026-06-24 17:30:00

Missing values per column:

Id                        0
Start                     0
End                       0
Updated                 929
UpdatedBy                 0
Status                    0
WorkFormCourse          695
WorkFormExam           2875
WorkFormEvaluation     2907
LearningEnvironment    2336
ExamEnvironment        2906
Classgroups             663
TeacherIds              656
OlodPointers            663
Rooms                    29
TrajectoryPart          663
dtype: int64

In [14]:
# checkss
if 'Status' in df.columns:
    print("Unique statuses:")
    print(df['Status'].value_counts())

# Example: Look at upcoming reservations after but more used to see from a certain date
from datetime import datetime
today = pd.Timestamp.today()

if 'Start' in df_clean.columns:
    upcoming = df_clean[df_clean['Start'] > today]
    print(f"Upcoming reservations after {today.date()}: {len(upcoming)}")
    display(upcoming.head(5))

Unique statuses:
Status
Confirmed    2907
Cancelled     406
Name: count, dtype: int64
Upcoming reservations after 2025-10-15: 2372

,Id,Start,End,Updated,UpdatedBy,Status,WorkFormCourse,WorkFormExam,WorkFormEvaluation,LearningEnvironment,ExamEnvironment,Classgroups,TeacherIds,OlodPointers,Rooms,TrajectoryPart
0,475972,2025-10-28 10:30:00,2025-10-28 12:30:00,2025-06-10 07:49:20,jan.soons+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01.02.130.006|01.02.130.014,NaN
1,475973,2025-10-16 10:30:00,2025-10-16 12:30:00,2025-06-10 08:05:22,suzanne.naert+1@hogent.be,Confirmed,Activerend hoorcollege,NaN,NaN,NaN,NaN,5922436,869611223154,193503,01.20.120.158,23621|23626|22996|23619
5,437295,2025-10-16 15:45:00,2025-10-16 16:45:00,2025-06-10 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,Onderwijsleergesprek,NaN,NaN,Digitaal (laptop/PC),NaN,5940368,869792953462,195982,21.03.125.047,23283
6,437296,2025-10-23 15:45:00,2025-10-23 16:45:00,2025-06-10 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,Onderwijsleergesprek,NaN,NaN,Digitaal (laptop/PC),NaN,5940368,869792953462,195982,21.03.125.047,23283
7,437297,2025-10-30 15:45:00,2025-10-30 16:45:00,2025-06-10 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,Onderwijsleergesprek,NaN,NaN,Digitaal (laptop/PC),NaN,5940368,869792953462,195982,21.03.125.047,23283

In [15]:
df

,Id,Start,End,Updated,UpdatedBy,Status,ReasonTeacher,ReasonRoom,InternExtern,Department,...,Classgroups,TeacherIds,OlodPointers,Rooms,TrajectoryPart,GroupHogent,Person,Student,Invigilator,source_file
0,475972,10/28/2025 10:30:00,10/28/2025 12:30:00,10/06/2025 07:49:20,jan.soons+1@hogent.be,Confirmed,NaN,NaN,NaN,UGent,...,NaN,NaN,NaN,01.02.130.006|01.02.130.014,NaN,NaN,NaN,NaN,NaN,TEreservations_20251006_20251007.csv
1,475973,10/16/2025 10:30:00,10/16/2025 12:30:00,10/06/2025 08:05:22,suzanne.naert+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,...,5922436,869611223154,193503,01.20.120.158,23621|23626|22996|23619,NaN,NaN,NaN,NaN,TEreservations_20251006_20251007.csv
2,413184,10/09/2025 08:15:00,10/09/2025 10:15:00,10/06/2025 08:05:34,NaN,Cancelled,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TEreservations_20251006_20251007.csv
3,437293,10/02/2025 15:45:00,10/02/2025 16:45:00,10/06/2025 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,...,5940368,869792953462,195982,21.03.125.047,23283,NaN,NaN,NaN,NaN,TEreservations_20251006_20251007.csv
4,437294,10/09/2025 15:45:00,10/09/2025 16:45:00,10/06/2025 08:07:03,Charlotte.christiaens+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,...,5940368,869792953462,195982,21.03.125.047,23283,NaN,NaN,NaN,NaN,TEreservations_20251006_20251007.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3308,434494,02/11/2026 13:30:00,02/11/2026 15:30:00,10/14/2025 21:40:47,katia.decanne+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,...,6005354|5889159,869332787886,195529,26.01.100.021,22886,NaN,NaN,NaN,NaN,TEreservations_20251014_20251015.csv
3309,434507,02/25/2026 15:45:00,02/25/2026 17:45:00,10/14/2025 21:42:58,katia.decanne+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,...,6005354|5889159,869332787886,195529,26.01.110.116,22886,NaN,NaN,NaN,NaN,TEreservations_20251014_20251015.csv
3310,434500,03/25/2026 13:30:00,03/25/2026 15:30:00,10/14/2025 21:44:13,katia.decanne+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,...,6005354|5889159,869332787886,195529,26.01.110.141,22886,NaN,NaN,NaN,NaN,TEreservations_20251014_20251015.csv
3311,434511,03/25/2026 15:45:00,03/25/2026 17:45:00,10/14/2025 21:44:45,katia.decanne+1@hogent.be,Confirmed,NaN,NaN,NaN,NaN,...,6005354|5889159,869332787886,195529,26.01.110.141,22886,NaN,NaN,NaN,NaN,TEreservations_20251014_20251015.csv
3312,478258,10/17/2025 10:00:00,10/17/2025 11:30:00,10/14/2025 21:50:25,yana.cattoir@student.hogent.be,Confirmed,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,21.07.110.026,NaN,NaN,NaN,859239638503,NaN,TEreservations_20251014_20251015.csv