In [2]:
from sqlalchemy import create_engine
from dotenv import load_dotenv
from datetime import datetime, timedelta
import os
import requests
import pandas as pd
import time

In [4]:
os.getcwd()

'c:\\Users\\Semih\\Desktop\\JAAR3\\DEP2 Project\\DEP2-2025-2026-groep12\\scraping'

In [5]:
import pandas as pd
import glob

# Path to your folder
folder_path = "../data/week1_4_wifi/"

# Find all parquet files in that folder
parquet_files = glob.glob(folder_path + "*.parquet")

# Read and concatenate them into one DataFrame
df = pd.concat([pd.read_parquet(file) for file in parquet_files], ignore_index=True)

# Check result
print(f"Loaded {len(parquet_files)} files into one DataFrame with {len(df)} rows.")

Loaded 21 files into one DataFrame with 921526 rows.

In [6]:
dftest = pd.read_parquet('../data/week1_4_wifi/wifi_stats_20251013_15min_intervals.parquet')
dftest_wifi = dftest[dftest["ssid"] == "eduroam"]

In [7]:
dftest_wifi

,site_id,family,model,os,manufacture,ap_id,ssid,wlan_id,username,proto,...,num_locating_aps,uptime,last_seen,dual_band,is_guest,channel,_pseudonymized,_pseudonymized_at,time_slot,email
0,c7206857-586f-460a-8ef9-a0f01963739b,iOS,,iOS,Apple,00000000-0000-0000-1000-a8537d085b0b,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_01a67e02f57f7e3f713307c09fe2f48704e0da4e60c9...,ax,...,1,310,1760386820,True,False,132,True,2025-11-03T08:53:17.271132,2025-10-13 20:30:00,u_f1345a73a269d2af967a668353a739d6c319fcb2e3a5...
1,c7206857-586f-460a-8ef9-a0f01963739b,iPhone,,18.6.2,Apple,00000000-0000-0000-1000-3c94fd03cf00,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_894e570495352b8c65abe54985569be356031fa96e11...,ax,...,1,253,1760387492,True,False,36,True,2025-11-03T08:53:17.271139,2025-10-13 20:30:00,u_f4144f4c5ef0c023d630b24d5c76567a9fde5b128be7...
2,c7206857-586f-460a-8ef9-a0f01963739b,Apple,,Apple OS,Apple,00000000-0000-0000-1000-3c94fd082168,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_e48ee71fcb542e39f8ee621e265bd5b95acad04fdb26...,ax,...,1,1,1760387624,True,False,11,True,2025-11-03T08:53:17.271144,2025-10-13 20:30:00,u_573c270e52806e9ae31b7de5eefef2f2c02cb89e5a1a...
3,c7206857-586f-460a-8ef9-a0f01963739b,Mac,,Catalina,Apple,00000000-0000-0000-1000-3c94fd03ce38,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_ddcc6da1146f209744c39727b4f9645f59aa5f77f52e...,ax,...,1,15047,1760388234,True,False,108,True,2025-11-03T08:53:17.271147,2025-10-13 20:30:00,u_74ac7e713d24afc8fbf83ef290a17c3e43dbc1c7c228...
4,c7206857-586f-460a-8ef9-a0f01963739b,,,Windows 10/11,Intel Corporate,00000000-0000-0000-1000-3c94fd03e84b,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_bdf2aa1f9eaab97ad0048d5a77bfbf6aa5e2bd9748a2...,ax,...,1,3779,1760388180,True,False,100,True,2025-11-03T08:53:17.271151,2025-10-13 20:30:00,u_a9ea373d9ca3147ed41755491a89102ec255d1a8c70c...
5,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 16,Unknown,00000000-0000-0000-1000-3c94fd08424c,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_9623b05b407369409031ec7bd44ef8758abe4bee6726...,ax,...,1,400,1760387960,True,False,124,True,2025-11-03T08:53:17.271155,2025-10-13 20:30:00,u_d134013751351e7fe0c372dda43ae001fadeb65278b8...
7,c7206857-586f-460a-8ef9-a0f01963739b,,,Windows 10/11,Intel Corporate,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_32373278c8331c49c282992c76bb394394a724762435...,ac,...,1,30093,1760388193,True,False,60,True,2025-11-03T08:53:17.271161,2025-10-13 20:30:00,u_5a1c5b7e98583d30048fd095a378e86cc8c188802f0c...
9,c7206857-586f-460a-8ef9-a0f01963739b,Mac,,Catalina,Apple,00000000-0000-0000-1000-3c94fd03ca00,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_50c261f44cc0dd500434aac58d6ca4f7ead63a43a215...,ax,...,1,29848,1760388209,True,False,132,True,2025-11-03T08:53:17.271167,2025-10-13 20:30:00,u_35b7e9baa2d1da63288bac76126e4c3d97a2c1f2cdec...
11,c7206857-586f-460a-8ef9-a0f01963739b,Mac,,Catalina,Apple,00000000-0000-0000-1000-3c94fd03ce38,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_ddcc6da1146f209744c39727b4f9645f59aa5f77f52e...,ax,...,1,15342,1760388540,True,False,108,True,2025-11-03T08:53:17.271173,2025-10-13 20:45:00,u_74ac7e713d24afc8fbf83ef290a17c3e43dbc1c7c228...
12,c7206857-586f-460a-8ef9-a0f01963739b,,,Windows 10/11,Intel Corporate,00000000-0000-0000-1000-3c94fd03e84b,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_bdf2aa1f9eaab97ad0048d5a77bfbf6aa5e2bd9748a2...,ax,...,1,4071,1760388484,True,False,100,True,2025-11-03T08:53:17.271176,2025-10-13 20:45:00,u_a9ea373d9ca3147ed41755491a89102ec255d1a8c70c...
13,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 16,Unknown,00000000-0000-0000-1000-3c94fd08424c,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_9623b05b407369409031ec7bd44ef8758abe4bee6726...,ax,...,1,400,1760387960,True,False,124,True,2025-11-03T08:53:17.271180,2025-10-13 20:45:00,u_d134013751351e7fe0c372dda43ae001fadeb65278b8...
15,c7206857-586f-460a-8ef9-a0f01963739b,,,Windows 10/11,Intel Corporate,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_32373278c8331c49c282992c76bb394394a724762435...,ac,...,1,30387,1760388499,True,False,60,True,2025-11-03T08:53:17.271186,2025-10-13 20:45:00,u_5a1c5b7e98583d30048fd095a378e86cc8c188802f0c...
17,c7206857-586f-460a-8ef9-a0f01963739b,Mac,,Catalina,Apple,00000000-0000-0000-1000-3c94fd03ca00,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_50c261f44cc0dd500434aac58d6ca4f7ead63a43a215...,ax,...,1,30139,1760388511,True,False,132,True,2025-11-03T08:53:17.271192,2025-10-13 20:45:00,u_35b7e9baa2d1da63288bac76126e4c3d97a2c1f2cdec...

In [8]:
df

,site_id,family,model,os,manufacture,ap_id,ssid,wlan_id,username,proto,...,num_locating_aps,uptime,last_seen,dual_band,is_guest,channel,_pseudonymized,_pseudonymized_at,time_slot,email
0,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 12,Unknown,00000000-0000-0000-1000-3c94fd03e8f5,hgguest,cc45c32f-8095-481b-affa-970258d817ef,,ac,...,1,33323,1758759218,False,True,100,True,2025-11-03T08:52:22.908789,2025-09-25 00:00:00,
1,c7206857-586f-460a-8ef9-a0f01963739b,Mac,,Catalina,Apple,00000000-0000-0000-1000-3c94fd03ce38,hgevent,93d5d431-b8b2-41ea-b4aa-65ad04bdd764,,ax,...,1,4057,1758759208,True,False,6,True,2025-11-03T08:52:22.908804,2025-09-25 00:00:00,
2,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 10,Unknown,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_9f12b8b71b86bd326b7f45e32355990fa30ee6c1c6ef...,ac,...,1,39875,1758759221,True,False,52,True,2025-11-03T08:52:22.908828,2025-09-25 00:00:00,u_6044e39dcdb91ff89d2a89c388d66a78f2c2dfa6b6ff...
3,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 10,Unknown,00000000-0000-0000-1000-3c94fd03ce9c,hgevent,93d5d431-b8b2-41ea-b4aa-65ad04bdd764,,ac,...,1,123468,1758759184,False,False,52,True,2025-11-03T08:52:22.908831,2025-09-25 00:00:00,
4,c7206857-586f-460a-8ef9-a0f01963739b,,,,Unknown,00000000-0000-0000-1000-3c94fd03cf00,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_77fcab55d1b0630b1a24432c09497701d3c7823252ec...,ax,...,1,276,1758758847,True,False,100,True,2025-11-03T08:52:22.908836,2025-09-25 00:00:00,u_20fe13de8f92b3c9ff67eb32229818a71f7ad5cd0740...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921521,c7206857-586f-460a-8ef9-a0f01963739b,,,Windows 8,Intel Corporate,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_896a35bb6b1b52aa0717cf89592d617ef15f7702fbe6...,ac,...,1,8130,1760572695,True,False,60,True,2025-11-03T08:53:24.817152,2025-10-15 23:45:00,u_e43101efdc46d19eac421784af7e2e491ebd448a4100...
921522,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 10,Unknown,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_9f12b8b71b86bd326b7f45e32355990fa30ee6c1c6ef...,n,...,1,41470,1760572695,True,False,6,True,2025-11-03T08:53:24.817156,2025-10-15 23:45:00,u_6044e39dcdb91ff89d2a89c388d66a78f2c2dfa6b6ff...
921523,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 12,Xiaomi Communications Co Ltd,00000000-0000-0000-1000-3c94fd03e8a5,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_c403891eb9af9cb6e757b9333a8bf4bb032d1804a855...,ax,...,1,38910,1760572700,True,False,44,True,2025-11-03T08:53:24.817160,2025-10-15 23:45:00,u_52c11e9312ec183c11f57c355a19ce74b77a829a5b09...
921524,c7206857-586f-460a-8ef9-a0f01963739b,,,,Unknown,00000000-0000-0000-1000-3c94fd03ce2e,hgevent,93d5d431-b8b2-41ea-b4aa-65ad04bdd764,,ac,...,1,2864314,1760572723,True,False,124,True,2025-11-03T08:53:24.817163,2025-10-15 23:45:00,
921525,c7206857-586f-460a-8ef9-a0f01963739b,,,Linux,Hui Zhou Gaoshengda Technology Co.,00000000-0000-0000-1000-3c94fd03e91d,iotroam,dc810e4a-3221-472a-ac58-66d550c0f788,,n,...,1,81266,1760572695,False,False,6,True,2025-11-03T08:53:24.817165,2025-10-15 23:45:00,

In [ ]:
# df_wifi_edu = df[df["ssid"] == "eduroam"]

In [ ]:
# df_wifi_edu

,site_id,family,model,os,manufacture,ap_id,ssid,wlan_id,username,proto,...,num_locating_aps,uptime,last_seen,dual_band,is_guest,channel,_pseudonymized,_pseudonymized_at,time_slot,email
2,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 10,Unknown,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_9f12b8b71b86bd326b7f45e32355990fa30ee6c1c6ef...,ac,...,1,39875,1758759221,True,False,52,True,2025-11-03T08:52:22.908828,2025-09-25 00:00:00,u_6044e39dcdb91ff89d2a89c388d66a78f2c2dfa6b6ff...
4,c7206857-586f-460a-8ef9-a0f01963739b,,,,Unknown,00000000-0000-0000-1000-3c94fd03cf00,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_77fcab55d1b0630b1a24432c09497701d3c7823252ec...,ax,...,1,276,1758758847,True,False,100,True,2025-11-03T08:52:22.908836,2025-09-25 00:00:00,u_20fe13de8f92b3c9ff67eb32229818a71f7ad5cd0740...
7,c7206857-586f-460a-8ef9-a0f01963739b,,,,Unknown,00000000-0000-0000-1000-3c94fd03cf00,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_77fcab55d1b0630b1a24432c09497701d3c7823252ec...,ax,...,1,276,1758758847,True,False,100,True,2025-11-03T08:52:22.908846,2025-09-25 00:15:00,u_20fe13de8f92b3c9ff67eb32229818a71f7ad5cd0740...
10,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 10,Unknown,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_9f12b8b71b86bd326b7f45e32355990fa30ee6c1c6ef...,ac,...,1,40698,1758760077,True,False,52,True,2025-11-03T08:52:22.908858,2025-09-25 00:15:00,u_6044e39dcdb91ff89d2a89c388d66a78f2c2dfa6b6ff...
12,c7206857-586f-460a-8ef9-a0f01963739b,,,Microsoft OS,Intel Corporate,00000000-0000-0000-1000-3c94fd03e84b,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_de170e0b62fc17ef3140f9a3d77ddd9d268e620115d1...,ax,...,1,441,1758760092,False,False,132,True,2025-11-03T08:52:22.908864,2025-09-25 00:15:00,u_90fb887724cd311483ac4df315e358285afbec4e1a47...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921517,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 10,Unknown,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_9f12b8b71b86bd326b7f45e32355990fa30ee6c1c6ef...,n,...,1,40643,1760571835,True,False,6,True,2025-11-03T08:53:24.817137,2025-10-15 23:30:00,u_6044e39dcdb91ff89d2a89c388d66a78f2c2dfa6b6ff...
921518,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 12,Xiaomi Communications Co Ltd,00000000-0000-0000-1000-3c94fd03e8a5,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_c403891eb9af9cb6e757b9333a8bf4bb032d1804a855...,ax,...,1,38028,1760571782,True,False,44,True,2025-11-03T08:53:24.817142,2025-10-15 23:30:00,u_52c11e9312ec183c11f57c355a19ce74b77a829a5b09...
921521,c7206857-586f-460a-8ef9-a0f01963739b,,,Windows 8,Intel Corporate,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_896a35bb6b1b52aa0717cf89592d617ef15f7702fbe6...,ac,...,1,8130,1760572695,True,False,60,True,2025-11-03T08:53:24.817152,2025-10-15 23:45:00,u_e43101efdc46d19eac421784af7e2e491ebd448a4100...
921522,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 10,Unknown,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_9f12b8b71b86bd326b7f45e32355990fa30ee6c1c6ef...,n,...,1,41470,1760572695,True,False,6,True,2025-11-03T08:53:24.817156,2025-10-15 23:45:00,u_6044e39dcdb91ff89d2a89c388d66a78f2c2dfa6b6ff...
921523,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 12,Xiaomi Communications Co Ltd,00000000-0000-0000-1000-3c94fd03e8a5,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,u_c403891eb9af9cb6e757b9333a8bf4bb032d1804a855...,ax,...,1,38910,1760572700,True,False,44,True,2025-11-03T08:53:24.817160,2025-10-15 23:45:00,u_52c11e9312ec183c11f57c355a19ce74b77a829a5b09...

In [9]:
# # Filter rows based on column: 'username'
# df_wifi_edu_test = df_wifi_edu[df_wifi_edu['username'] == "u_f7e456322f77b44776a279acd119948ed08bad928fa3d1fa752f7e8ee6967abf"]

In [10]:
# df_wifi_edu_test

In [9]:
# Functions for dataframe processing and writing to datawarehouse
def insert_new_users(df_wifi_edu, engine, df_existing_users):
    """Function for writing new users to DimUser table."""
    df_new_users = df_wifi_edu[["username"]].drop_duplicates()

    # List of existing usernames
    existing_usernames = df_existing_users.tolist()

    # Keep only usernames not in existing_usernames
    not_existing = []
    for username in df_new_users["username"]:
        if username not in existing_usernames:
            not_existing.append(username)

    df_new_users = df_new_users[
        df_new_users["username"].isin(not_existing)
    ]  # Only keep the usernames that are in not_existing
    df_new_users = df_new_users.rename(columns={"username": "UserName"})

    # Write to database if any new users exist
    if not df_new_users.empty:
        df_new_users.to_sql("DimUser", engine, if_exists="append", index=False)
        print(f"Added {len(df_new_users)} new users to DimUser.")
    else:
        print("No new users to add.")

In [10]:
def map_user_keys(df_wifi_edu, engine):
    """Function to map UserKeys to usernames in df_wifi_edu (needed for inserting into FactWifiConnection -> DateKey, TimeKey, UserKey)"""
    df_existing_users = pd.read_sql("SELECT UserKey, UserName FROM DimUser", engine)
    user_keys = []

    # Add UserKey to user_keys if username from df_wifi_edu matches username in df_existing_users
    for username in df_wifi_edu["username"]:
        match = df_existing_users[df_existing_users["UserName"] == username]
        if not match.empty:
            user_keys.append(match.iloc[0]["UserKey"])
        else:
            user_keys.append(None)

    # Now all usernames in df_wifi_edu have a corresponding UserKey
    df_wifi_edu["UserKey"] = user_keys
    return df_wifi_edu

In [11]:
def insert_new_fact_rows(df_wifi_edu, engine):
    """Function for writing wifi connections to FactWifiConnection table"""
    # Keep only the relevant columns and remove duplicates
    fact_wifi_connection = (
        df_wifi_edu[["DateKey", "TimeKey", "UserKey"]]
        .drop_duplicates()
        .reset_index(drop=True)
    )

    # Read existing rows from the database
    existing_keys = pd.read_sql(
        "SELECT DateKey, TimeKey, UserKey FROM FactWifiConnection", engine
    )

    # Merge to find new rows (those not in existing)
    fact_wifi_connection = fact_wifi_connection.merge(
        existing_keys, on=["DateKey", "TimeKey", "UserKey"], how="left", indicator=True
    )

    # Keep only rows that are in fact_wifi_connection but not in existing_keys
    fact_wifi_connection = fact_wifi_connection[
        fact_wifi_connection["_merge"] == "left_only"
    ]
    fact_wifi_connection = fact_wifi_connection.drop(columns="_merge")

    # Insert into database if any new rows exist
    if not fact_wifi_connection.empty:
        fact_wifi_connection.to_sql(
            "FactWifiConnection", engine, if_exists="append", index=False
        )
        print(f"Inserted {len(fact_wifi_connection)} new rows into FactWifiConnection.")
    else:
        print("No new FactWifiConnection rows to insert.")

In [12]:
# SQL Server config inside the VM
server = "127.0.0.1,1500"
database = "DEP2_staging"
username = "sa"
password = "dep2025-G12"
driver = "ODBC Driver 17 for SQL Server"

engine = create_engine(
    f"mssql+pyodbc://{username}:{password}@{server}/{database}?driver={driver}"
)

# # SQL Server config local
# server = "LAPTOP-R1GLLN97"
# database = "DEP2Test"
# driver = "ODBC Driver 17 for SQL Server"

# # Create database-engine
# engine = create_engine(
#     f"mssql+pyodbc://@{server}/{database}?trusted_connection=yes&driver={driver}"
# )

df_wifi_edu = df[df["ssid"] == "eduroam"]

# Adjust timestamp to Brussels timezone
df_wifi_edu["timestamp"] = (
    pd.to_datetime(df_wifi_edu["timestamp"], utc=True)
    .dt.tz_convert("Europe/Brussels")
    .dt.tz_localize(None)  # remove timezone info -> naive local datetimes
)

# round timestamp to the closest 5 minutes
df_wifi_edu["timestamp"] = df_wifi_edu["timestamp"].dt.round("5min")

# Create DateKey and TimeKey columns
df_wifi_edu["DateKey"] = df_wifi_edu["timestamp"].dt.strftime("%Y%m%d").astype(int)
df_wifi_edu["TimeKey"] = df_wifi_edu["timestamp"].dt.strftime("%H%M%S").astype(int)

C:\Users\Semih\AppData\Local\Temp\ipykernel_13812\2821652608.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_wifi_edu["timestamp"] = (
C:\Users\Semih\AppData\Local\Temp\ipykernel_13812\2821652608.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_wifi_edu["timestamp"] = df_wifi_edu["timestamp"].dt.round("5min")
C:\Users\Semih\AppData\Local\Temp\ipykernel_13812\2821652608.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_wifi_edu["DateKey"] = df_wifi_edu["timestamp"].dt.strftime("%Y%m%d").astype(int)
C:\Users\Semih\AppData\Local\Temp\ipykernel_13812\2821652608.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_wifi_edu["TimeKey"] = df_wifi_edu["timestamp"].dt.strftime("%H%M%S").astype(int)

In [13]:
# Drop existing username column and rename email column to username
df_wifi_edu = df_wifi_edu.drop(columns=['username'])
df_wifi_edu = df_wifi_edu.rename(columns={'email': 'username'})

In [14]:
df_wifi_edu

,site_id,family,model,os,manufacture,ap_id,ssid,wlan_id,proto,band,...,last_seen,dual_band,is_guest,channel,_pseudonymized,_pseudonymized_at,time_slot,username,DateKey,TimeKey
2,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 10,Unknown,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,ac,5,...,1758759221,True,False,52,True,2025-11-03T08:52:22.908828,2025-09-25 00:00:00,u_6044e39dcdb91ff89d2a89c388d66a78f2c2dfa6b6ff...,20250925,21500
4,c7206857-586f-460a-8ef9-a0f01963739b,,,,Unknown,00000000-0000-0000-1000-3c94fd03cf00,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,ax,5,...,1758758847,True,False,100,True,2025-11-03T08:52:22.908836,2025-09-25 00:00:00,u_20fe13de8f92b3c9ff67eb32229818a71f7ad5cd0740...,20250925,21500
7,c7206857-586f-460a-8ef9-a0f01963739b,,,,Unknown,00000000-0000-0000-1000-3c94fd03cf00,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,ax,5,...,1758758847,True,False,100,True,2025-11-03T08:52:22.908846,2025-09-25 00:15:00,u_20fe13de8f92b3c9ff67eb32229818a71f7ad5cd0740...,20250925,22000
10,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 10,Unknown,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,ac,5,...,1758760077,True,False,52,True,2025-11-03T08:52:22.908858,2025-09-25 00:15:00,u_6044e39dcdb91ff89d2a89c388d66a78f2c2dfa6b6ff...,20250925,23000
12,c7206857-586f-460a-8ef9-a0f01963739b,,,Microsoft OS,Intel Corporate,00000000-0000-0000-1000-3c94fd03e84b,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,ax,5,...,1758760092,False,False,132,True,2025-11-03T08:52:22.908864,2025-09-25 00:15:00,u_90fb887724cd311483ac4df315e358285afbec4e1a47...,20250925,23000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921517,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 10,Unknown,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,n,24,...,1760571835,True,False,6,True,2025-11-03T08:53:24.817137,2025-10-15 23:30:00,u_6044e39dcdb91ff89d2a89c388d66a78f2c2dfa6b6ff...,20251016,14500
921518,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 12,Xiaomi Communications Co Ltd,00000000-0000-0000-1000-3c94fd03e8a5,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,ax,5,...,1760571782,True,False,44,True,2025-11-03T08:53:24.817142,2025-10-15 23:30:00,u_52c11e9312ec183c11f57c355a19ce74b77a829a5b09...,20251016,14500
921521,c7206857-586f-460a-8ef9-a0f01963739b,,,Windows 8,Intel Corporate,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,ac,5,...,1760572695,True,False,60,True,2025-11-03T08:53:24.817152,2025-10-15 23:45:00,u_e43101efdc46d19eac421784af7e2e491ebd448a4100...,20251016,20000
921522,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 10,Unknown,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,n,24,...,1760572695,True,False,6,True,2025-11-03T08:53:24.817156,2025-10-15 23:45:00,u_6044e39dcdb91ff89d2a89c388d66a78f2c2dfa6b6ff...,20251016,20000
921523,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 12,Xiaomi Communications Co Ltd,00000000-0000-0000-1000-3c94fd03e8a5,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,ax,5,...,1760572700,True,False,44,True,2025-11-03T08:53:24.817160,2025-10-15 23:45:00,u_52c11e9312ec183c11f57c355a19ce74b77a829a5b09...,20251016,20000

In [15]:
df_wifi_edu.dropna(subset=['username'], inplace=True)

In [16]:
df_wifi_edu

,site_id,family,model,os,manufacture,ap_id,ssid,wlan_id,proto,band,...,last_seen,dual_band,is_guest,channel,_pseudonymized,_pseudonymized_at,time_slot,username,DateKey,TimeKey
2,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 10,Unknown,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,ac,5,...,1758759221,True,False,52,True,2025-11-03T08:52:22.908828,2025-09-25 00:00:00,u_6044e39dcdb91ff89d2a89c388d66a78f2c2dfa6b6ff...,20250925,21500
4,c7206857-586f-460a-8ef9-a0f01963739b,,,,Unknown,00000000-0000-0000-1000-3c94fd03cf00,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,ax,5,...,1758758847,True,False,100,True,2025-11-03T08:52:22.908836,2025-09-25 00:00:00,u_20fe13de8f92b3c9ff67eb32229818a71f7ad5cd0740...,20250925,21500
7,c7206857-586f-460a-8ef9-a0f01963739b,,,,Unknown,00000000-0000-0000-1000-3c94fd03cf00,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,ax,5,...,1758758847,True,False,100,True,2025-11-03T08:52:22.908846,2025-09-25 00:15:00,u_20fe13de8f92b3c9ff67eb32229818a71f7ad5cd0740...,20250925,22000
10,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 10,Unknown,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,ac,5,...,1758760077,True,False,52,True,2025-11-03T08:52:22.908858,2025-09-25 00:15:00,u_6044e39dcdb91ff89d2a89c388d66a78f2c2dfa6b6ff...,20250925,23000
12,c7206857-586f-460a-8ef9-a0f01963739b,,,Microsoft OS,Intel Corporate,00000000-0000-0000-1000-3c94fd03e84b,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,ax,5,...,1758760092,False,False,132,True,2025-11-03T08:52:22.908864,2025-09-25 00:15:00,u_90fb887724cd311483ac4df315e358285afbec4e1a47...,20250925,23000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921517,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 10,Unknown,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,n,24,...,1760571835,True,False,6,True,2025-11-03T08:53:24.817137,2025-10-15 23:30:00,u_6044e39dcdb91ff89d2a89c388d66a78f2c2dfa6b6ff...,20251016,14500
921518,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 12,Xiaomi Communications Co Ltd,00000000-0000-0000-1000-3c94fd03e8a5,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,ax,5,...,1760571782,True,False,44,True,2025-11-03T08:53:24.817142,2025-10-15 23:30:00,u_52c11e9312ec183c11f57c355a19ce74b77a829a5b09...,20251016,14500
921521,c7206857-586f-460a-8ef9-a0f01963739b,,,Windows 8,Intel Corporate,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,ac,5,...,1760572695,True,False,60,True,2025-11-03T08:53:24.817152,2025-10-15 23:45:00,u_e43101efdc46d19eac421784af7e2e491ebd448a4100...,20251016,20000
921522,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 10,Unknown,00000000-0000-0000-1000-3c94fd03e91d,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,n,24,...,1760572695,True,False,6,True,2025-11-03T08:53:24.817156,2025-10-15 23:45:00,u_6044e39dcdb91ff89d2a89c388d66a78f2c2dfa6b6ff...,20251016,20000
921523,c7206857-586f-460a-8ef9-a0f01963739b,,,Android 12,Xiaomi Communications Co Ltd,00000000-0000-0000-1000-3c94fd03e8a5,eduroam,f6f56648-82d3-4084-9d82-61552b2d8f9e,ax,5,...,1760572700,True,False,44,True,2025-11-03T08:53:24.817160,2025-10-15 23:45:00,u_52c11e9312ec183c11f57c355a19ce74b77a829a5b09...,20251016,20000

In [17]:
# filter df_wifi_edu to missing usernames
df_wifi_edu[df_wifi_edu["username"].isnull()]

Empty DataFrame
Columns: [site_id, family, model, os, manufacture, ap_id, ssid, wlan_id, proto, band, vlan_id, key_mgmt, map_id, annotation, timestamp, assoc_time, rssi, snr, idle_time, tx_rate, rx_rate, tx_pkts, rx_pkts, tx_bytes, rx_bytes, tx_retries, rx_retries, tx_bps, rx_bps, x, y, x_m, y_m, num_locating_aps, uptime, last_seen, dual_band, is_guest, channel, _pseudonymized, _pseudonymized_at, time_slot, username, DateKey, TimeKey]
Index: []

[0 rows x 45 columns]

In [18]:
# Get existing usernames from DimUser in datawarehouse to make sure we only add new users to DimUser
df_existing_users = pd.read_sql("SELECT UserName FROM DimUser", engine)["UserName"]

In [19]:
df_existing_users

0        u_794cdf75162dfff2df8449d8c09720daa2a91206304a...
1        u_0e24b17496fbfd848527cc479ee51e4b46282675a5bd...
2        u_8e551770dbe974db0286b03cf15f18b69c39b458faf1...
3        u_0a33d71358267d7418733dec6c689fb5cd5580afbf3d...
4        u_5391984464c112a7d58ba16a425fd2d4973176ed66df...
                               ...
26569    u_dcb8b1bd8672ac17745d886d8523103ea17b260dd1fc...
26570    u_81c953c691ce77bfd7a9a51d2fac59aba9201914233b...
26571    u_330581736703f9fc53e4c9703a143323600089cde5e6...
26572    u_074810639620cf31dd42461173e5c284965519c73ce0...
26573    u_3c20bcba801f184de78d0e796ac56affbd780350accf...
Name: UserName, Length: 26574, dtype: object

In [25]:
# Write new users to DimUser
insert_new_users(df_wifi_edu, engine, df_existing_users)

Added 8284 new users to DimUser.

In [26]:
# Map UserKeys to usernames in df_wifi_edu, which is needed for FactWifiConnection
df_wifi_edu = map_user_keys(df_wifi_edu, engine)

C:\Users\Semih\AppData\Local\Temp\ipykernel_27776\38671426.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_wifi_edu["UserKey"] = user_keys

In [27]:
# Write all wifi connections to FactWifiConnection
insert_new_fact_rows(df_wifi_edu, engine)

Inserted 597601 new rows into FactWifiConnection.